#!/bin/bash

# A "mix test" that allows you to have symlinks in deps/

set -eu -o pipefail

MIX_ENV=test  mix deps.compile
HEX_OFFLINE=1 mix test --no-elixir-version-check --no-deps-check --no-archives-check --trace "$@"
